# Generated by Django 5.2.10 on 2026-02-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date_time", models.DateTimeField(blank=True, null=True)),
                ("venue_name", models.CharField(blank=True, max_length=255)),
                ("venue_address", models.TextField(blank=True)),
                ("city", models.CharField(default="Sydney", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField(blank=True)),
                ("source_name", models.CharField(max_length=100)),
                ("source_url", models.URLField(unique=True)),
                ("last_scraped_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("updated", "Updated"),
                            ("inactive", "Inactive"),
                            ("imported", "Imported"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("imported_by", models.CharField(blank=True, max_length=100)),
                ("import_notes", models.TextField(blank=True)),
            ],
        ),
    ]
